apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-repo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-repo
  template:
    metadata:
      labels:
        app: my-app-repo
    spec:
      containers:
      - name: my-app-repo
        image: 970547346793.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
